feat(changelog)!: breaking changes are never skipped
orhun/git-cliff pull request #114
Opened 2022-10-01 17:12 UTC by sbmueller

Hi there! Trying to contribute to this project first-time.

## Description
Trying to resolve #106 by excluding breaking changes from being skipped, even when matched by a skipping commit parser.

## Motivation and Context

Breaking changes are highly relevant for stakeholders, therefore should not be skipped in a changelog, even when matched by commit parsers.
This could be extended by a setting, if the former assumption is not considered true most of the time. Happy to follow up on that.

Fixes #106 

## How Has This Been Tested?

Extended the test cases by breaking change commits. Added a usual breaking change commit and one that matches a skipped commit parser regex. The latter is not skipped even it matches a commit parser that has `skip` set to true.

nightly-aarch64-apple-darwin / rustc 1.66.0-nightly (8ce3204af 2022-09-30)

Backward compatibility is provided. Existing changelogs might change because of this change though.

## Screenshots / Output (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-10-03 20:05 UTC, orhun requested changes
LGTM! Just a few edits needed, see my comments 🐻

2022-10-03 20:07 UTC, orhun commented
I added test fixtures for this PR in [4e61f30](https://github.com/orhun/git-cliff/pull/114/commits/4e61f30412e4dd3f4780e808831e818f2b2020b3)

2022-10-04 17:52 UTC, sbmueller commented on git-cliff-core/src/config.rs
> +	pub protect_breaking_commits: Option<bool>,
Went with `false` here to maintain backward compatibility

2022-10-04 17:54 UTC, sbmueller commented on git-cliff-core/src/commit.rs
> +	/// breaking, or parser's `skip` field is None or `false` returns `false`.
Rephrased it a bit, hope it is better now

2022-10-04 17:56 UTC, sbmueller commented on README.md
> +
Oops, wasn't intentional

2022-10-04 17:59 UTC, sbmueller commented
Thanks @orhun for the review! I think I addressed everything now. Feel free to add more comments if unsure about something.

2022-10-04 20:21 UTC, orhun approved these changes
Great stuff, thanks for your contribution! 🐻

2022-10-04 20:21 UTC, merged