feat: allow returning bumped version
orhun/git-cliff pull request #362
Opened 2023-12-01 13:59 UTC by nappa85

## Description

This PR adds a CLI command to simply return the bumped version, solves #361 

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] I have formatted the code with [rustfmt](https://github.com/rust-lang/rustfmt).
- [x] I checked the lints with [clippy](https://github.com/rust-lang/rust-clippy).
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-12-03 16:17 UTC, orhun requested changes
Had some comments - please check 🐻 

Can you also add [fixture tests](https://github.com/orhun/git-cliff/tree/main/.github/fixtures) for testing the output?

2023-12-03 16:17 UTC, orhun commented on git-cliff/src/args.rs
> +	pub bumped_version: bool,
Not sure if I like the argument name. We can go with `--print-version` or something similar. What do you think?

2023-12-03 16:17 UTC, orhun commented on git-cliff/src/lib.rs
> +}
Can you document the enum/fields for clarity?

2023-12-03 16:17 UTC, orhun commented on website/docs/usage/examples.md
> +```
We can merge this with this example above to avoid the duplicate explanation of SemVer.

2023-12-04 19:06 UTC, orhun approved these changes
Thanks for your contribution! 💖

2023-12-04 19:09 UTC, merged

2023-12-04 19:48 UTC, nappa85 commented
> Thanks for your contribution! 💖

Thank you for your patience