fix(commit): pass footer token and separator to template
orhun/git-cliff pull request #97
Opened 2022-06-24 16:48 UTC by hawkw

## Description

This branch changes the `Serialize` impl for `Commit` to output conventional
commit footers as structured JSON objects, rather than as just the footer's
value string.

See hawkw/git-cliff@93779b21667fd5f7ec28635e36e428035d69afb5 for a discussion of
the implementation details of this change.

## Motivation and Context

As discussed in issue #96, using footers in changelog templates is currently not
practical in most cases, since there is currently no way to determine *which*
footer a value belongs to, and no way to access the name of the footer.

This PR implements the approach suggested by @orhun in
https://github.com/orhun/git-cliff/issues/96#issuecomment-1164883227.
Additionally, I added a section to the README documentation discussing the
structure of the footers passed to templates.

Fixes #96

## How Has This Been Tested?

I added a new test in `commit.rs` that conventional commits with footers have a
`footers` iterator containing the correct footers. In addition, I did some
manual testing to test the use of footers in templates --- see the next section
for details.

## Screenshots / Output (if appropriate):

To manually verify that everthing works end-to-end, I temporarily modified
`examples/detailed.toml` to output footers in the template:

```patch
diff --git a/examples/detailed.toml b/examples/detailed.toml
index b6b57fd..6fc2252 100644
--- a/examples/detailed.toml
+++ b/examples/detailed.toml
@@ -24,6 +24,9 @@ body = """
     ### {{ group | upper_first }}
     {% for commit in commits %}
         - {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}]({{ commit.id }}))\
+          {% for footer in commit.footers -%}
+            , {{ footer.token }}{{ footer.separator }} {{ footer.value }}\
+          {% endfor %}
     {% endfor %}
 {% endfor %}\n
 """
```

Generating a test changelog with that template now outputs footers, as expected:

```markdown
# Changelog

All notable changes to this project will be documented in this file.

## [unreleased]

### Documentation

- Clarify that `--tag` argument can be an unexisting tag ([d540f5d](d540f5d8938bc84b01b4fafaa69c3290eb72cd08))

- Discuss footers in README ([a54bca5](a54bca57acc91a886d52bb9d3d87866eb5c18f32)), Signed-off-by: Eliza Weisman <eliza@buoyant.io>

### Features

- Support external commands for commit preprocessors (#86) ([7d0786c](7d0786ca55423950f0779de4e6a907fc25ae203a))

- Support changing commit scope with `commit_parsers` (#94) ([e220768](e22076843b91be3680617db5686e070dedcfef29)), Co-authored-by: Orhun Parmaksız <orhunparmaksiz@gmail.com>

...
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ ] Other 

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-06-25 22:59 UTC, orhun requested changes
Had a couple of nitpicks here and there but looks great! 💯 

Can you also add test fixtures for this change as well? I might do it after merge if you don't want to include in the PR, no problem.

2022-06-25 22:59 UTC, orhun commented on git-cliff-core/src/commit.rs
> +impl<'a> From<&'a git_conventional::Footer<'a>> for Footer<'a> {
Can we move this implementation right after the struct definition of `Footer`?

2022-06-25 22:59 UTC, orhun commented on git-cliff-core/src/commit.rs
> +		/// `Serializer::collect_seq` without having to
This seems like an unfinished comment, I didn't quite understand what it means, can you update it?

2022-06-25 22:59 UTC, orhun commented on README.md
> +[trailers]: https://git-scm.com/docs/git-interpret-trailers)
This doesn't seem to be rendered correctly due to trailing ")" character. Also, can you use in-place links (`[alt](url)`) instead to make it aligned with the rest of README.md?

2022-06-25 23:04 UTC, orhun commented
> ```diff
> diff --git a/examples/detailed.toml b/examples/detailed.toml
> index b6b57fd..6fc2252 100644
> --- a/examples/detailed.toml
> +++ b/examples/detailed.toml
> @@ -24,6 +24,9 @@ body = """
>      ### {{ group | upper_first }}
>      {% for commit in commits %}
>          - {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}]({{ commit.id }}))\
> +          {% for footer in commit.footers -%}
> +            , {{ footer.token }}{{ footer.separator }} {{ footer.value }}\
> +          {% endfor %}
>      {% endfor %}
>  {% endfor %}\n
>  """
> ```

Ah, also include this change in the PR please. It seems like a good way to demonstrate how footers can be used within template.

2022-06-30 07:21 UTC, orhun commented
Hey @hawkw, can you take a look at this PR soon? I would like to include it in the next release of `git-cliff` if possible 🐻

2022-07-01 18:04 UTC, hawkw commented
Sorry, I didn't have a chance to follow up sooner. I'll go ahead and address the remaining feedback, thanks!

2022-07-01 18:06 UTC, hawkw commented
> > ```diff
> > diff --git a/examples/detailed.toml b/examples/detailed.toml
> > index b6b57fd..6fc2252 100644
> > --- a/examples/detailed.toml
> > +++ b/examples/detailed.toml
> > @@ -24,6 +24,9 @@ body = """
> >      ### {{ group | upper_first }}
> >      {% for commit in commits %}
> >          - {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}]({{ commit.id }}))\
> > +          {% for footer in commit.footers -%}
> > +            , {{ footer.token }}{{ footer.separator }} {{ footer.value }}\
> > +          {% endfor %}
> >      {% endfor %}
> >  {% endfor %}\n
> >  """
> > ```
> 
> Ah, also include this change in the PR please. It seems like a good way to demonstrate how footers can be used within template.

Sure, happy to do that! One quick question, though: is there an example repository you're using to generate the example changelogs in the README? I would want to re-generate the "detailed" example now that the template has changed.

2022-07-01 18:14 UTC, hawkw commented
> Can you also add test fixtures for this change as well? I might do it after merge if you don't want to include in the PR, no problem.



> Can you also add test fixtures for this change as well? I might do it after merge if you don't want to include in the PR, no problem.

I added some tests for commits with footers in `commit.rs`, here: https://github.com/orhun/git-cliff/blob/9f78b0cb5498a1db6129167eee162b97978011cb/git-cliff-core/src/commit.rs#L354-L404

Are there other tests you're referring to? I'm happy to add any other tests that are necessary for this change, but I wasn't sure where else you would want to test this.

2022-07-06 10:51 UTC, orhun commented
> I added some tests for commits with footers in `commit.rs`, here:

Yup, it looks good 👍🏼 

 > Are there other tests you're referring to? I'm happy to add any other tests that are necessary for this change, but I wasn't sure where else you would want to test this.

There are fixture tests in `.github/fixtures` for testing the functionality of `git-cliff` by running it with a pre-defined commit history. It is not super important, but nice to have. Like I said, I can work on it after merging the PR if that's something that you'd not prefer to add 🙂

2022-07-06 17:44 UTC, hawkw commented
> > Are there other tests you're referring to? I'm happy to add any other tests that are necessary for this change, but I wasn't sure where else you would want to test this.
> 
> There are fixture tests in `.github/fixtures` for testing the functionality of `git-cliff` by running it with a pre-defined commit history. It is not super important, but nice to have. Like I said, I can work on it after merging the PR if that's something that you'd not prefer to add slightly_smiling_face

Oh, I see, I missed those. I'll figure out how to add those tests as well.

2022-07-12 12:33 UTC, orhun commented
> Oh, I see, I missed those. I'll figure out how to add those tests as well.

I just added fixture tests and made some tweaks to the `detailed.toml` example. Merging, thanks for the PR!

2022-07-12 12:36 UTC, orhun approved these changes

2022-07-12 12:38 UTC, merged